os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim --headless -c 'normal {{line}}G' -c 'startinsert' {{filename}}"
  openDirInEditor: "nvim {{dir}}"
  editInTerminal: true
gui:
  theme:
    activeBorderColor:
      - "#FFB454"
      - bold
    inactiveBorderColor:
      - "#E7C08A"
    optionsTextColor:
      - "#FFB454"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#59C2FF"
    unstagedChangesColor:
      - "#F07178"
    defaultFgColor:
      - "#39BAE6"
    searchingActiveBorderColor:
      - "#FFB454"

  authorColors:
    "*": "#AAD94C"
